// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtPGcfSitqfyBDUY20Gq9l6dV-cQ0YDJo',
    appId: '1:104582409738:web:07b3026a59de618624f9f3',
    messagingSenderId: '104582409738',
    projectId: 'fasum-516b7',
    authDomain: 'fasum-516b7.firebaseapp.com',
    storageBucket: 'fasum-516b7.appspot.com',
    measurementId: 'G-4LV37C88QD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzn0ASck8xkrI70KUwwvc_lMstkA4ljlo',
    appId: '1:104582409738:android:60a322c12239207924f9f3',
    messagingSenderId: '104582409738',
    projectId: 'fasum-516b7',
    storageBucket: 'fasum-516b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4kVRIqBKnJaas1UKDpz8H07SOKbbxvew',
    appId: '1:104582409738:ios:76ede9cde90f42b924f9f3',
    messagingSenderId: '104582409738',
    projectId: 'fasum-516b7',
    storageBucket: 'fasum-516b7.appspot.com',
    iosBundleId: 'com.example.fasilitasUmum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4kVRIqBKnJaas1UKDpz8H07SOKbbxvew',
    appId: '1:104582409738:ios:5854a4a5dc8dd4ec24f9f3',
    messagingSenderId: '104582409738',
    projectId: 'fasum-516b7',
    storageBucket: 'fasum-516b7.appspot.com',
    iosBundleId: 'com.example.fasilitasUmum.RunnerTests',
  );
}
